const JSON_HEADERS={"content-type":"application/json; charset=UTF-8","cache-control":"no-store"};
function cors(request,env){const o=request.headers.get('Origin')||'',a=(env.ALLOWED_ORIGIN||'').replace(/\/$/,'');const ok=(a&&o===a)||/^https:\/\/[a-z0-9-]+\.github\.io$/i.test(o);return {'Access-Control-Allow-Origin':ok?o:'null','Access-Control-Allow-Methods':'GET,POST,PUT,OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Credentials':'true','Vary':'Origin'}}
function json(d,s,r,e){return new Response(JSON.stringify(d),{status:s,headers:{...JSON_HEADERS,...cors(r,e)}})}
function okOrigin(r,e){const o=r.headers.get('Origin')||'',a=(e.ALLOWED_ORIGIN||'').replace(/\/$/,'');return (a&&o===a)||/^https:\/\/[a-z0-9-]+\.github\.io$/i.test(o)}
async function body(r){try{return await r.json()}catch{throw Error('请求体不是有效 JSON')}}
function id(){return crypto.randomUUID()}
function b64(u8){let s='';for(const x of u8)s+=String.fromCharCode(x);return btoa(s).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function unb64(s){s=s.replaceAll('-','+').replaceAll('_','/');while(s.length%4)s+='=';const bin=atob(s);return Uint8Array.from(bin,c=>c.charCodeAt(0))}
async function sha256(text){return b64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))))}
async function hashPassword(password,salt){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:100000,hash:'SHA-256'},key,256);return b64(new Uint8Array(bits))}
async function makePassword(password){if(typeof password!=='string'||password.length<8||password.length>200)throw Error('密码需要 8-200 个字符');const salt=crypto.getRandomValues(new Uint8Array(16));return b64(salt)+'.'+await hashPassword(password,salt)}
async function verifyPassword(password,stored){const [s,h]=String(stored).split('.');if(!s||!h)return false;return await hashPassword(password,unb64(s))===h}
async function newSession(userId){const raw=b64(crypto.getRandomValues(new Uint8Array(32)));return {raw,hash:await sha256(raw),userId,expires:Date.now()+30*24*3600*1000}}
async function auth(r,e){const h=r.headers.get('Authorization')||'';if(!h.startsWith('Bearer '))return null;const hash=await sha256(h.slice(7));const row=await e.DB.prepare('SELECT user_id,expires_at FROM sessions WHERE id_hash=?').bind(hash).first();if(!row||Number(row.expires_at)<Date.now()){if(row)await e.DB.prepare('DELETE FROM sessions WHERE id_hash=?').bind(hash).run();return null}return row.user_id}
async function sendCode(r,e){
 await e.DB.prepare('CREATE TABLE IF NOT EXISTS registration_otps (email TEXT PRIMARY KEY,code_hash TEXT NOT NULL,name TEXT NOT NULL,password_hash TEXT NOT NULL,expires_at INTEGER NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,last_sent_at INTEGER NOT NULL)').run();
 const x=await body(r),email=String(x.email||'').trim().toLowerCase(),password=String(x.password||''),name=String(x.name||'').trim().slice(0,80);
 if(!/^\S+@\S+\.\S+$/.test(email))throw Error('请输入有效邮箱');
 if(name.length<1)throw Error('请输入姓名');
 if(await e.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first())throw Error('这个邮箱已经注册');
 const old=await e.DB.prepare('SELECT last_sent_at FROM registration_otps WHERE email=?').bind(email).first();
 if(old&&Date.now()-Number(old.last_sent_at)<60000)throw Error('验证码发送过于频繁，请 60 秒后再试');
 const code=String(Math.floor(100000+Math.random()*900000));
 const ph=await makePassword(password),ch=await sha256(email+':'+code),now=Date.now(),expires=now+10*60*1000;
 await e.DB.prepare('INSERT INTO registration_otps(email,code_hash,name,password_hash,expires_at,attempts,last_sent_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(email) DO UPDATE SET code_hash=excluded.code_hash,name=excluded.name,password_hash=excluded.password_hash,expires_at=excluded.expires_at,attempts=0,last_sent_at=excluded.last_sent_at').bind(email,ch,name,ph,expires,0,now).run();
 const from=e.EMAIL_FROM||'onboarding@resend.dev';
 if(!e.RESEND_API_KEY)throw Error('服务器尚未配置邮箱发送服务');
 const mail=await fetch('https://api.resend.com/emails',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${e.RESEND_API_KEY}`},body:JSON.stringify({from,to:[email],subject:'猫星作息助手注册验证码',html:`<div style="font-family:Arial,sans-serif;line-height:1.7"><h2>猫星作息助手</h2><p>你的注册验证码是：</p><div style="font-size:32px;font-weight:700;letter-spacing:8px">${code}</div><p>验证码 10 分钟内有效。如果不是你本人操作，请忽略这封邮件。</p></div>`})});
 if(!mail.ok){const t=await mail.text();throw Error('验证码邮件发送失败：'+t.slice(0,180))}
 return json({ok:true,message:'验证码已发送，10 分钟内有效'},200,r,e)
}
async function register(r,e){
 const x=await body(r),email=String(x.email||'').trim().toLowerCase(),code=String(x.code||'').trim();
 if(!/^\S+@\S+\.\S+$/.test(email))throw Error('请输入有效邮箱');
 if(!/^\d{6}$/.test(code))throw Error('请输入 6 位验证码');
 const p=await e.DB.prepare('SELECT * FROM registration_otps WHERE email=?').bind(email).first();
 if(!p)throw Error('请先获取验证码');
 if(Number(p.expires_at)<Date.now())throw Error('验证码已过期，请重新获取');
 if(Number(p.attempts)>=5)throw Error('验证码错误次数过多，请重新获取');
 const ok=await sha256(email+':'+code)===p.code_hash;
 if(!ok){await e.DB.prepare('UPDATE registration_otps SET attempts=attempts+1 WHERE email=?').bind(email).run();throw Error('验证码不正确')}
 if(await e.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first())throw Error('这个邮箱已经注册');
 const uid=id(),now=Date.now();
 await e.DB.batch([e.DB.prepare('INSERT INTO users(id,email,password_hash,name,created_at) VALUES(?,?,?,?,?)').bind(uid,email,p.password_hash,p.name,now),e.DB.prepare('INSERT INTO profiles(user_id,data_json,updated_at) VALUES(?,?,?)').bind(uid,JSON.stringify(defaultProfile()),now),e.DB.prepare('DELETE FROM registration_otps WHERE email=?').bind(email)]);
 const ss=await newSession(uid);await e.DB.prepare('INSERT INTO sessions(id_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)').bind(ss.hash,uid,ss.expires,now).run();
 return json({ok:true,user:{id:uid,email,name:p.name},token:ss.raw},200,r,e)
}

async function login(r,e){const x=await body(r),email=String(x.email||'').trim().toLowerCase(),password=String(x.password||''),u=await e.DB.prepare('SELECT id,email,name,password_hash FROM users WHERE email=?').bind(email).first();if(!u||!(await verifyPassword(password,u.password_hash)))return json({error:'邮箱或密码不正确'},401,r,e);const s=await newSession(u.id);await e.DB.prepare('INSERT INTO sessions(id_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)').bind(s.hash,u.id,s.expires,Date.now()).run();return json({ok:true,user:{id:u.id,email:u.email,name:u.name},token:s.raw},200,r,e)}
function defaultProfile(){return {sleep:{workHours:8,restHours:8.5,bedtime:'23:00',latestWake:'07:30'},meals:{breakfast:30,lunch:30,dinner:30},life:{wash:20,laundry:20,commute:10},nap:{enabled:true,min:20,max:30},exercise:{enabled:true,min:30,max:60},study:[{title:'写作业',minutes:60,priority:5},{title:'学编程',minutes:45,priority:4},{title:'学英语',minutes:30,priority:3}],rules:{protectSleep:true,protectClasses:true,preferContinuousFocus:true,buffer:10}}}
async function profile(r,e,uid){if(r.method==='GET'){const row=await e.DB.prepare('SELECT data_json FROM profiles WHERE user_id=?').bind(uid).first();return json(row?JSON.parse(row.data_json):defaultProfile(),200,r,e)}const x=await body(r);await e.DB.prepare('INSERT INTO profiles(user_id,data_json,updated_at) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET data_json=excluded.data_json,updated_at=excluded.updated_at').bind(uid,JSON.stringify(x),Date.now()).run();return json({ok:true,profile:x},200,r,e)}
function cleanCourse(c){const title=String(c.title||'未命名课程').trim().slice(0,120),day=String(c.day||'周一'),start=String(c.start||'08:00'),end=String(c.end||'08:45');const periods=Math.max(1,Math.min(12,Number(c.periods||1)));if(!['周一','周二','周三','周四','周五','周六','周日'].includes(day))throw Error('课程星期无效');if(!/^\d{2}:\d{2}$/.test(start)||!/^\d{2}:\d{2}$/.test(end)||start>=end)throw Error('课程时间无效');return {id:String(c.id||id()),title,day,start,end,periods,room:String(c.room||'').slice(0,100),color:String(c.color||'#dbeafe').slice(0,20),type:String(c.type||'课程').slice(0,30)}}
async function courses(r,e,uid){const url=new URL(r.url),week=Math.max(1,Math.min(52,Number(url.searchParams.get('week')||1)));if(r.method==='GET'){const rows=await e.DB.prepare('SELECT id,day,title,start_time start,end_time end,periods,room,color,type FROM courses WHERE user_id=? AND week=? ORDER BY day,start_time').bind(uid,week).all();return json({week,courses:rows.results||[]},200,r,e)}const x=await body(r),list=Array.isArray(x.courses)?x.courses.map(cleanCourse):[];for(let i=0;i<list.length;i++){for(let j=i+1;j<list.length;j++){const c=list[i],d=list[j];if(c.day===d.day&&c.start<d.end&&d.start<c.end)throw Error('课程时间存在重叠：'+c.day+' '+c.title+' / '+d.title)}}const stmts=[e.DB.prepare('DELETE FROM courses WHERE user_id=? AND week=?').bind(uid,week),...list.map(c=>e.DB.prepare('INSERT INTO courses(id,user_id,week,day,title,start_time,end_time,periods,room,color,type,data_json,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(c.id,uid,week,c.day,c.title,c.start,c.end,c.periods,c.room,c.color,c.type,'{}',Date.now()))];await e.DB.batch(stmts);return json({ok:true,week,courses:list},200,r,e)}
function hm(t){const m=/^(\d{2}):(\d{2})$/.exec(String(t||''));if(!m)return NaN;const h=+m[1],n=+m[2];return h>=0&&h<24&&n>=0&&n<60?h*60+n:NaN}
async function validateStoredSchedule(e,uid,week,s){const rows=await e.DB.prepare('SELECT day,title,start_time start,end_time end FROM courses WHERE user_id=? AND week=?').bind(uid,week).all();const cs=rows.results||[];const expected=[...new Set(cs.map(c=>c.day))];if(Number(s?.week)!==week||!Array.isArray(s?.days)||s.days.length!==expected.length||s.days.some(d=>!expected.includes(d.day)))throw Error('schedule 天数与当前课程不一致');for(const d of s.days){if(!['周一','周二','周三','周四','周五','周六','周日'].includes(d.day)||!Array.isArray(d.items))throw Error('schedule 星期或项目无效');const items=d.items.map(x=>({x,a:hm(x.start),b:hm(x.end)})).sort((a,b)=>a.a-b.a);for(let i=0;i<items.length;i++){if(!Number.isFinite(items[i].a)||!Number.isFinite(items[i].b)||items[i].b<=items[i].a)throw Error('schedule 存在无效时间');if(i&&items[i].a<items[i-1].b)throw Error('schedule 存在时间重叠');}for(const c of cs.filter(c=>c.day===d.day)){const n=items.filter(v=>v.x.title===c.title&&v.x.start===c.start&&v.x.end===c.end);if(n.length!==1)throw Error('schedule 未完整保留课程硬约束：'+c.day+' '+c.title+' '+c.start+'–'+c.end)}for(const x of items){const sameTitle=cs.find(c=>c.day===d.day&&c.title===x.x.title);if(sameTitle&&!(x.x.start===sameTitle.start&&x.x.end===sameTitle.end))throw Error('schedule 修改了固定课程时间：'+d.day+' '+x.x.title)}}}
async function schedule(r,e,uid){const url=new URL(r.url),week=Math.max(1,Math.min(52,Number(url.searchParams.get('week')||1)));if(r.method==='GET'){const row=await e.DB.prepare('SELECT data_json FROM schedules WHERE user_id=? AND week=?').bind(uid,week).first();return json({week,schedule:row?JSON.parse(row.data_json):null},200,r,e)}const x=await body(r);if(!x.schedule)throw Error('schedule 缺失');await validateStoredSchedule(e,uid,week,x.schedule);await e.DB.prepare('INSERT INTO schedules(id,user_id,week,data_json,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(user_id,week) DO UPDATE SET data_json=excluded.data_json,updated_at=excluded.updated_at').bind(id(),uid,week,JSON.stringify(x.schedule),Date.now()).run();return json({ok:true,week,schedule:x.schedule},200,r,e)}
async function checkin(r,e,uid){const x=await body(r),date=String(x.date||'').slice(0,20),item=String(x.item||'').slice(0,160),done=x.done?1:0;if(!date||!item)throw Error('打卡数据不完整');await e.DB.prepare('INSERT INTO checkins(id,user_id,date_key,item_key,done,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(user_id,date_key,item_key) DO UPDATE SET done=excluded.done,updated_at=excluded.updated_at').bind(id(),uid,date,item,done,Date.now()).run();return json({ok:true},200,r,e)}
function validateImage(image){if(typeof image!=='string'||!image.startsWith('data:image/'))throw Error('image 必须是 data:image Base64');if(image.length>18*1024*1024)throw Error('图片过大')}
async function zhipu(r,e){const x=await body(r);validateImage(x.image);const up=await fetch('https://open.bigmodel.cn/api/paas/v4/chat/completions',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${e.ZHIPU_API_KEY}`},body:JSON.stringify({model:x.model||'glm-4.6v',temperature:0,top_p:.1,messages:[{role:'user',content:[{type:'text',text:String(x.prompt||'')},{type:'image_url',image_url:{url:x.image}}]}]})});return new Response(await up.text(),{status:up.status,headers:{...JSON_HEADERS,...cors(r,e)}})}
async function deepseek(r,e){const x=await body(r);if(!Array.isArray(x.messages)||!x.messages.length)throw Error('messages 无效');const up=await fetch('https://api.deepseek.com/chat/completions',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${e.DEEPSEEK_API_KEY}`},body:JSON.stringify({model:x.model||'deepseek-chat',messages:x.messages,temperature:typeof x.temperature==='number'?x.temperature:.2})});return new Response(await up.text(),{status:up.status,headers:{...JSON_HEADERS,...cors(r,e)}})}
export default {async fetch(r,e){const u=new URL(r.url);if(r.method==='OPTIONS'){if(!okOrigin(r,e))return new Response(null,{status:403,headers:cors(r,e)});return new Response(null,{status:204,headers:cors(r,e)})}if(!okOrigin(r,e))return json({error:'Origin not allowed'},403,r,e);try{if(r.method==='GET'&&u.pathname==='/')return json({ok:true,service:'schedule-ai-proxy',version:'v4',endpoints:['/auth/send-code','/auth/register','/auth/login','/auth/logout','/auth/me','/api/profile','/api/courses','/api/schedule','/api/checkin','/zhipu','/deepseek']},200,r,e);if(u.pathname==='/auth/send-code'&&r.method==='POST')return await sendCode(r,e);if(u.pathname==='/auth/register'&&r.method==='POST')return await register(r,e);if(u.pathname==='/auth/login'&&r.method==='POST')return await login(r,e);if(u.pathname==='/auth/logout'&&r.method==='POST'){const h=r.headers.get('Authorization')||'';if(h.startsWith('Bearer '))await e.DB.prepare('DELETE FROM sessions WHERE id_hash=?').bind(await sha256(h.slice(7))).run();return json({ok:true},200,r,e)}if(u.pathname==='/auth/me'&&r.method==='GET'){const uid=await auth(r,e);if(!uid)return json({user:null},200,r,e);const row=await e.DB.prepare('SELECT id,email,name FROM users WHERE id=?').bind(uid).first();return json({user:row||null},200,r,e)}if(['/api/profile','/api/courses','/api/schedule','/api/checkin'].includes(u.pathname)){const uid=await auth(r,e);if(!uid)return json({error:'需要登录'},401,r,e);if(u.pathname==='/api/profile')return await profile(r,e,uid);if(u.pathname==='/api/courses')return await courses(r,e,uid);if(u.pathname==='/api/schedule')return await schedule(r,e,uid);return await checkin(r,e,uid)}if(r.method==='POST'&&(u.pathname==='/zhipu'||u.pathname==='/deepseek')){const uid=await auth(r,e);if(!uid)return json({error:'需要登录'},401,r,e);if(u.pathname==='/zhipu')return await zhipu(r,e);return await deepseek(r,e)}return json({error:'Not found'},404,r,e)}catch(err){return json({error:err?.message||'Worker error'},400,r,e)}}};